snowflake-dw:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: xkb49714.us-east-1

      #user/password auth
      user: AIRBYTE_USER
      password: AIRBYTE_PASSWORD

      role: AIRBYTE_ROLE
      database: AIRBYTE_DATABASE
      warehouse: AIRBYTE_WAREHOUSE
      schema: AIRBYTE_SCHEMA
      client_session_keep_alive: False
      query_tag: db-q

      #optional
      connect_retries: 0
      connect_timeout: 10
      retry_on_database_errors: False
      rerty_all: False